#ifndef CONFIG_H
#define CONFIG_H

#include "driver/gpio.h"

// WARNING: SERVO AND SPEAKER MIGHT NOT WORK SIMULTANEOUSLY ON 3.3V POWER SUPPLY

#define LOCK_SERVO_PIN GPIO_NUM_25
#define UNLOCK_BUTTON_PIN GPIO_NUM_27 // UNLOCK BUTTON IS SECOND FROM THE TOP
#define LOCK_BUTTON_PIN GPIO_NUM_14   // LOCK BUTTON IS AT THE VERY TOP

#define BUZZER_PIN GPIO_NUM_26        

#define STATUS_LED_BUILTIN GPIO_NUM_2
#define STATUS_LED_RED GPIO_NUM_12      // LOCKED LED IS AT THE VERY TOP
#define STATUS_LED_UNLOCKED GPIO_NUM_13 // UNLOCKED LED IS SECOND FROM THE TOP

#define USE_SERVO_MOTOR 1

#if USE_SERVO_MOTOR
#define SERVO_LOCKED_ANGLE 0
#define SERVO_UNLOCKED_ANGLE 90
#define SERVO_PWM_FREQ 50
#define SERVO_MIN_PULSE_US 500
#define SERVO_MAX_PULSE_US 2500
#else
#define RELAY_ACTIVE_LOW 0
#endif

#define BUTTON_DEBOUNCE_MS 50      // button debounce delay
#define AUTO_LOCK_TIMEOUT_MS 30000  // auto-lock after 30 seconds
#define SERVO_MOVE_TIME_MS 500     // time for servo to complete movement

typedef enum
{
    LOCK_STATE_LOCKED,
    LOCK_STATE_UNLOCKING,
    LOCK_STATE_UNLOCKED,
    LOCK_STATE_ERROR
} lock_state_t;

typedef enum
{
    EVENT_LOCK,
    EVENT_UNLOCK,
    EVENT_BUTTON_PRESS,
    EVENT_REMOTE_UNLOCK
} event_type_t;

// UPDATE BEFORE WIFI DEPLOYMENT
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define MQTT_BROKER_URI "mqtt://broker.hivemq.com"
#define MQTT_PORT 1883
#define MQTT_TOPIC_STATUS "boltlock/status"
#define MQTT_TOPIC_COMMAND "boltlock/command"
#define MQTT_TOPIC_EVENTS "boltlock/events"

#define TELEGRAM_BOT_TOKEN "8211750808:AAHjzySteM0FmwT3G3QCZfk2xbQWTI0TLuQ"
#define TELEGRAM_CHAT_ID "7286752705"

#define NVS_NAMESPACE "boltlock"
#define NVS_LOCK_STATE_KEY "lock_state"
#define NVS_EVENT_COUNT_KEY "event_count"

#endif // CONFIG_H